module.exports = {
  taxtypes: {
    application: {
      fetchAll: 'TaxType_fetchAll',
      fetchById: 'TaxType_fetchById',
      create: 'TaxType_create',
      delete: 'TaxType_delete',
      update: 'TaxType_update',
    },
    db: {
      fetchAll: 'DB_TaxType_fetchAll',
      fetchById: 'DB_TaxType_fetchById',
      create: 'DB_TaxType_create',
      delete: 'DB_TaxType_delete',
      update: 'DB_TaxType_update',
    },
  },
  uom: {
    application: {
      fetchAll: 'UOM_fetchAll',
      fetchById: 'UOM_fetchById',
      create: 'UOM_create',
      delete: 'UOM_delete',
      update: 'UOM_update',
    },
    db: {
      fetchAll: 'DB_UOM_fetchAll',
      fetchById: 'DB_UOM_fetchById',
      create: 'DB_UOM_create',
      delete: 'DB_UOM_delete',
      update: 'DB_UOM_update',
    },
  },
  categorydetail: {
    application: {
      fetchAll: 'CategoryDetail_fetchAll',
      fetchById: 'CategoryDetail_fetchById',
      create: 'CategoryDetail_create',
      delete: 'CategoryDetail_delete',
      update: 'CategoryDetail_update',
    },
    db: {
      fetchAll: 'DB_CategoryDetail_fetchAll',
      fetchById: 'DB_CategoryDetail_fetchById',
      create: 'DB_CategoryDetail_create',
      delete: 'DB_CategoryDetail_delete',
      update: 'DB_CategoryDetail_update',
    },
  },
  transactiontypeconfig: {
    application: {
      fetchAll: 'TransactionTypeConfig_fetchAll',
      fetchById: 'TransactionTypeConfig_fetchById',
      create: 'TransactionTypeConfig_create',
      delete: 'TransactionTypeConfig_delete',
      update: 'TransactionTypeConfig_update',
    },
    db: {
      fetchAll: 'DB_TransactionTypeConfig_fetchAll',
      fetchById: 'DB_TransactionTypeConfig_fetchById',
      create: 'DB_TransactionTypeConfig_create',
      delete: 'DB_TransactionTypeConfig_delete',
      update: 'DB_TransactionTypeConfig_update',
    },
  },
  organizationdetail: {
    application: {
      fetchAll: 'OrganizationDetail_fetchAll',
      fetchById: 'OrganizationDetail_fetchById',
      create: 'OrganizationDetail_create',
      delete: 'OrganizationDetail_delete',
      update: 'OrganizationDetail_update',
    },
    db: {
      fetchAll: 'DB_OrganizationDetail_fetchAll',
      fetchById: 'DB_OrganizationDetail_fetchById',
      create: 'DB_OrganizationDetail_create',
      delete: 'DB_OrganizationDetail_delete',
      update: 'DB_OrganizationDetail_update',
    },
  },
  uomfactor: {
    application: {
      fetchAll: 'UOMFactor_fetchAll',
      fetchById: 'UOMFactor_fetchById',
      create: 'UOMFactor_create',
      delete: 'UOMFactor_delete',
      update: 'UOMFactor_update',
    },
    db: {
      fetchAll: 'DB_UOMFactor_fetchAll',
      fetchById: 'DB_UOMFactor_fetchById',
      create: 'DB_UOMFactor_create',
      delete: 'DB_UOMFactor_delete',
      update: 'DB_UOMFactor_update',
    },
  },
  transactiontypes: {
    application: {
      fetchAll: 'TransactionType_fetchAll',
      fetchById: 'TransactionType_fetchById',
      create: 'TransactionType_create',
      delete: 'TransactionType_delete',
      update: 'TransactionType_update',
    },
    db: {
      fetchAll: 'DB_TransactionType_fetchAll',
      fetchById: 'DB_TransactionType_fetchById',
      create: 'DB_TransactionType_create',
      delete: 'DB_TransactionType_delete',
      update: 'DB_TransactionType_update',
    },
  },
  accounttypebase: {
    application: {
      fetchAll: 'AccountTypeBase_fetchAll',
      fetchById: 'AccountTypeBase_fetchById',
      create: 'AccountTypeBase_create',
      delete: 'AccountTypeBase_delete',
      update: 'AccountTypeBase_update',
    },
    db: {
      fetchAll: 'DB_AccountTypeBase_fetchAll',
      fetchById: 'DB_AccountTypeBase_fetchById',
      create: 'DB_AccountTypeBase_create',
      delete: 'DB_AccountTypeBase_delete',
      update: 'DB_AccountTypeBase_update',
    },
  },
  transactiontypestatus: {
    application: {
      fetchAll: 'TransactionTypeStatus_fetchAll',
      fetchById: 'TransactionTypeStatus_fetchById',
      create: 'TransactionTypeStatus_create',
      delete: 'TransactionTypeStatus_delete',
      update: 'TransactionTypeStatus_update',
    },
    db: {
      fetchAll: 'DB_TransactionTypeStatus_fetchAll',
      fetchById: 'DB_TransactionTypeStatus_fetchById',
      create: 'DB_TransactionTypeStatus_create',
      delete: 'DB_TransactionTypeStatus_delete',
      update: 'DB_TransactionTypeStatus_update',
    },
  },
  contactaddresstype: {
    application: {
      fetchAll: 'ContactAddressType_fetchAll',
      fetchById: 'ContactAddressType_fetchById',
      create: 'ContactAddressType_create',
      delete: 'ContactAddressType_delete',
      update: 'ContactAddressType_update',
    },
    db: {
      fetchAll: 'DB_ContactAddressType_fetchAll',
      fetchById: 'DB_ContactAddressType_fetchById',
      create: 'DB_ContactAddressType_create',
      delete: 'DB_ContactAddressType_delete',
      update: 'DB_ContactAddressType_update',
    },
  },
  taxgroup: {
    application: {
      fetchAll: 'TaxGroup_fetchAll',
      fetchById: 'TaxGroup_fetchById',
      create: 'TaxGroup_create',
      delete: 'TaxGroup_delete',
      update: 'TaxGroup_update',
    },
    db: {
      fetchAll: 'DB_TaxGroup_fetchAll',
      fetchById: 'DB_TaxGroup_fetchById',
      create: 'DB_TaxGroup_create',
      delete: 'DB_TaxGroup_delete',
      update: 'DB_TaxGroup_update',
    },
  },
  taxgrouptaxtypemapper: {
    application: {
      fetchAll: 'TaxGroupTaxTypeMapper_fetchAll',
      fetchById: 'TaxGroupTaxTypeMapper_fetchById',
      create: 'TaxGroupTaxTypeMapper_create',
      delete: 'TaxGroupTaxTypeMapper_delete',
      update: 'TaxGroupTaxTypeMapper_update',
      searchbyname: 'TaxGroupTaxTypeMapper_searchbyname',
    },
    db: {
      fetchAll: 'DB_TaxGroupTaxTypeMapper_fetchAll',
      fetchById: 'DB_TaxGroupTaxTypeMapper_fetchById',
      create: 'DB_TaxGroupTaxTypeMapper_create',
      delete: 'DB_TaxGroupTaxTypeMapper_delete',
      update: 'DB_TaxGroupTaxTypeMapper_update',
      searchbyname: 'DB_TaxGroupTaxTypeMapper_searchbyname',
    },
  },
  mapprovider: {
    application: {
      fetchAll: 'MapProvider_fetchAll',
      fetchById: 'MapProvider_fetchById',
      create: 'MapProvider_create',
      delete: 'MapProvider_delete',
      update: 'MapProvider_update',
    },
    db: {
      fetchAll: 'DB_MapProvider_fetchAll',
      fetchById: 'DB_MapProvider_fetchById',
      create: 'DB_MapProvider_create',
      delete: 'DB_MapProvider_delete',
      update: 'DB_MapProvider_update',
    },
  },
  locationdetail: {
    application: {
      fetchAll: 'LocationDetail_fetchAll',
      fetchById: 'LocationDetail_fetchById',
      create: 'LocationDetail_create',
      delete: 'LocationDetail_delete',
      update: 'LocationDetail_update',
    },
    db: {
      fetchAll: 'DB_LocationDetail_fetchAll',
      fetchById: 'DB_LocationDetail_fetchById',
      create: 'DB_LocationDetail_create',
      delete: 'DB_LocationDetail_delete',
      update: 'DB_LocationDetail_update',
    },
  },
  mapproviderlocationmapper: {
    application: {
      fetchAll: 'MapProviderLocationMapper_fetchAll',
      fetchById: 'MapProviderLocationMapper_fetchById',
      create: 'MapProviderLocationMapper_create',
      delete: 'MapProviderLocationMapper_delete',
      update: 'MapProviderLocationMapper_update',
    },
    db: {
      fetchAll: 'DB_MapProviderLocationMapper_fetchAll',
      fetchById: 'DB_MapProviderLocationMapper_fetchById',
      create: 'DB_MapProviderLocationMapper_create',
      delete: 'DB_MapProviderLocationMapper_delete',
      update: 'DB_MapProviderLocationMapper_update',
    },
  },
  contactdetail: {
    application: {
      fetchAll: 'ContactDetail_fetchAll',
      fetchById: 'ContactDetail_fetchById',
      create: 'ContactDetail_create',
      delete: 'ContactDetail_delete',
      update: 'ContactDetail_update',
      searchbyname: 'ContactDetail_searchbyname',
    },
    db: {
      fetchAll: 'DB_ContactDetail_fetchAll',
      fetchById: 'DB_ContactDetail_fetchById',
      create: 'DB_ContactDetail_create',
      delete: 'DB_ContactDetail_delete',
      update: 'DB_ContactDetail_update',
      searchbyname: 'DB_ContactDetail_searchbyname',
    },
  },
  addressdetail: {
    application: {
      fetchAll: 'AddressDetail_fetchAll',
      fetchById: 'AddressDetail_fetchById',
      create: 'AddressDetail_create',
      delete: 'AddressDetail_delete',
      update: 'AddressDetail_update',
    },
    db: {
      fetchAll: 'DB_AddressDetail_fetchAll',
      fetchById: 'DB_AddressDetail_fetchById',
      create: 'DB_AddressDetail_create',
      delete: 'DB_AddressDetail_delete',
      update: 'DB_AddressDetail_update',
      searchbyname: 'DB_AddressDetail_searchbyname',
    },
  },
  costinfo: {
    application: {
      fetchAll: 'CostInfo_fetchAll',
      fetchById: 'CostInfo_fetchById',
      create: 'CostInfo_create',
      delete: 'CostInfo_delete',
      update: 'CostInfo_update',
    },
    db: {
      fetchAll: 'DB_CostInfo_fetchAll',
      fetchById: 'DB_CostInfo_fetchById',
      create: 'DB_CostInfo_create',
      delete: 'DB_CostInfo_delete',
      update: 'DB_CostInfo_update',
      searchbyname: 'DB_ConstInfo_searchbyname',
    },
  },
  branchdetail: {
    application: {
      fetchAll: 'BranchDetail_fetchAll',
      fetchById: 'BranchDetail_fetchById',
      create: 'BranchDetail_create',
      delete: 'BranchDetail_delete',
      update: 'BranchDetail_update',
    },
    db: {
      fetchAll: 'DB_BranchDetail_fetchAll',
      fetchById: 'DB_BranchDetail_fetchById',
      create: 'DB_BranchDetail_create',
      delete: 'DB_BranchDetail_delete',
      update: 'DB_BranchDetail_update',
      searchbyname: 'DB_BranchDetail_searchbyname',
    },
  },
  branchusergroupmapper: {
    application: {
      fetchAll: 'BranchUserGroupMapper_fetchAll',
      fetchById: 'BranchUserGroupMapper_fetchById',
      create: 'BranchUserGroupMapper_create',
      delete: 'BranchUserGroupMapper_delete',
      update: 'BranchUserGroupMapper_update',
    },
    db: {
      fetchAll: 'DB_BranchUserGroupMapper_fetchAll',
      fetchById: 'DB_BranchUserGroupMapper_fetchById',
      create: 'DB_BranchUserGroupMapper_create',
      delete: 'DB_BranchUserGroupMapper_delete',
      update: 'DB_BranchUserGroupMapper_update',
      searchbyname: 'DB_BranchUserGroupMapper_searchbyname',
    },
  },
  batchdetail: {
    application: {
      fetchAll: 'BatchDetail_fetchAll',
      fetchById: 'BatchDetail_fetchById',
      create: 'BatchDetail_create',
      delete: 'BatchDetail_delete',
      update: 'BatchDetail_update',
    },
    db: {
      fetchAll: 'DB_BatchDetail_fetchAll',
      fetchById: 'DB_BatchDetail_fetchById',
      create: 'DB_BatchDetail_create',
      delete: 'DB_BatchDetail_delete',
      update: 'DB_BatchDetail_update',
      searchbyname: 'DB_BatchDetail_searchbyname',
    },
  },
  itemdetail: {
    application: {
      fetchAll: 'ItemDetail_fetchAll',
      fetchById: 'ItemDetail_fetchById',
      create: 'ItemDetail_create',
      delete: 'ItemDetail_delete',
      update: 'ItemDetail_update',
    },
    db: {
      fetchAll: 'DB_ItemDetail_fetchAll',
      fetchById: 'DB_ItemDetail_fetchById',
      create: 'DB_ItemDetail_create',
      delete: 'DB_ItemDetail_delete',
      update: 'DB_ItemDetail_update',
      searchbyname: 'DB_ItemDetail_searchbyname',
    },
  },
}
